config/routes.rb
ScoutSublimevideo::Application.routes.draw do
  # Sample of named route:
  get  'new/:day' => 'carousel#new_sites_day', as: 'new_sites_day'
  get  'active/:day' => 'carousel#new_active_sites_week', as: 'new_active_sites_week'
  post 'take/:token' => 'carousel#take', as: 'take'

  root to: redirect("/new/#{I18n.l(Time.now.yesterday.midnight, format: :Y_m_d)}")
end

app/models/screenshot.rb
class Screenshot
  include Mongoid::Document
  include Mongoid::Timestamps::Created

  field :u, type: String
  field :f, type: String

  embedded_in :site, class_name: 'ScreenshotedSite'

  mount_uploader :f, ScreenshotUploader

  validates :u, presence: true
end

app/models/screenshoted_site.rb
class ScreenshotedSite
  include Mongoid::Document
  include Mongoid::Timestamps
  include ApplicationHelper

  cattr_accessor :sites_infos

  MAX_ATTEMPTS = 5
  DELAY = proc { |count| count ** 2 }

  field :t,   type: String
  field :lfa, type: DateTime # last failed at => used for not retrying to take a screenshot everytime
  field :fac, type: Integer, default: 0 # failed attempts count
  index({ t: 1 }, { unique: true })

  embeds_many :screenshots, cascade_callbacks: true, store_as: 's' do
    def latest
      desc(:created_at).first
    end
  end

  validates :t, presence: true, uniqueness: true

  def self.cannot_be_retried(attempts)
    where(fac: attempts).where(:lfa.gte => ScreenshotedSite::DELAY.call(attempts).days.ago)
  end

  def self.with_max_attempts
    where(:fac.gte => ScreenshotedSite::MAX_ATTEMPTS)
  end

  # Returns the screenshoted sites corresponding to the given Site array
  #
  # @param [Array<Site>] sites array of Site instances
  def self.from_sites(sites)
    @@sites_infos = sites.inject({}) { |hash, s| hash[s.token] = s; hash }

    where(:t.in => sites.map(&:token))
  end

  # Returns the screenshoted sites corresponding to the given Site array
  # sorted by last_30_days_admin_starts DESC
  #
  # @param [Array<Site>] sites array of Site instances
  def self.from_sites_sorted_by_billable_views(sites)
    from_sites(sites).sort { |a, b| b.site_info.last_30_days_admin_starts <=> a.site_info.last_30_days_admin_starts }
  end

  def site_info
    @site_info ||= self.class.sites_infos[t]
  end

  # This method tells if the latest screenshot of a site is older than the
  # given days count.
  #
  # @param [Datetime] date the date to compare the latest screenshot to.
  #
  # @return [Boolean]
  def latest_screenshot_older_than?(date)
    screenshots.latest.nil? ||
    screenshots.latest.created_at.nil? ||
    screenshots.latest.created_at < date
  end

  def prepare_for_carousel
    if screenshot = screenshots.latest
      {
        token: t,
        thumb: screenshot ? screenshot.f.url(:carousel) : '/no-screenshot.png',
        link: screenshot ? screenshot.u : url_with_protocol(site_info.hostname),
        hostname: site_info.hostname,
        views: site_info.last_30_days_admin_starts,
        video_tags: site_info.last_30_days_video_tags,
        tags: site_info.tags.join(', ')
      }
    end
  end
end

app/models/site.rb
require 'sublime_video_private_api/model'

class Site
  include SublimeVideoPrivateApi::Model
  uses_private_api :my

  SKIPPED_DOMAINS = %w[please-edit.me test.com facebook.com youtube.com youtu.be vimeo.com dailymotion.com google.com dropbox.com dl.dropbox.com]

  def self.all_new_sites_for(timestamp)
    all(_default_params.merge(created_on: timestamp, by_date: 'desc', per: 1000))
  end

  def self.all_new_active_sites_for(timestamp)
    all(_default_params.merge(first_admin_starts_on_week: timestamp, by_last_30_days_admin_starts: 'desc', per: 1000))
  end

  def safe_status
    tags.include?('safe') ? 'safe' : 'not_safe'
  end

  def add_tag(tag)
    self.class.put(:add_tag, id: token, tag: tag)
  end

  private

  def self._default_params
    {
      select: %w[last_30_days_admin_starts last_30_days_video_tags],
      without_hostnames: SKIPPED_DOMAINS, not_tagged_with: 'adult'
    }
  end

end

app/models/site_stat_admin.rb
require 'sublime_video_private_api/model'

class SiteStatAdmin
  include SublimeVideoPrivateApi::Model
  uses_private_api :stats
  collection_path '/private_api/site_admin_stats'

  def self.by_hits_for(token)
    get_raw(:last_pages, site_token: token)[:parsed_data][:data]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/carousel_controller.rb
class CarouselController < ApplicationController
  respond_to :html

  before_filter :set_day
  before_filter :redirect_to_beginning_of_week, only: [:new_active_sites_week]

  protect_from_forgery except: [:take]

  def new_sites_day
    load_images(Site.all_new_sites_for(@day))
  end

  def new_active_sites_week
    load_images(Site.all_new_active_sites_for(@day))
  end

  def take
    ScreenshotWorker.perform_async(params[:token])
    render text: "Screenshot for #{params[:token]} will be re-taken!"
  end

  private

  def set_day
    @day = (params[:day] ? Time.parse(params[:day]) : Time.now.utc).midnight
  end

  def redirect_to_beginning_of_week
    redirect_to new_active_sites_week_url(l(@day.beginning_of_week, format: :Y_m_d)) unless @day == @day.beginning_of_week
  end

  def load_images(sites)
    @images = ScreenshotedSite.from_sites_sorted_by_billable_views(sites).map(&:prepare_for_carousel).compact.to_json
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(text, page_title = true)
    content_for :title, text
    content_tag(:h2, text, class: 'title') if page_title
  end

   def url_with_protocol(url)
    return '' if url.blank?
    (url =~ %r(^https?://) ? '' : 'http://') + url
  end

end

app/views/carousel/_carousel.html.slim
#carousel.page.view
  .origin.view
    #camera.view
      #dolly.view
        #stack.view
        #mirror.view
          #rstack.view

#caption.caption
  h4 Keyboard shortcuts
  ul
    li
      strong ↑↓
      em change day/week
    li
      strong ←→
      em scroll sites
    li
      strong space
      em toggle magnify
    li
      strong v
      em change view
    li
      strong t
      em= "view #{action_name == 'new_sites_day' ? 'yesterday' : 'last week'}"
    li
      strong o
      em open site
    li
      strong a
      em open admin
    li
      strong s
      em#slideshow_label start/stop slideshow
    li
      strong f
      em enter fullscreen

#info_bar style="display:none"
  = link_to 'i', '', class: 'admin_link', onclick: 'window.open(this);return false'
  = link_to 'example.com', '', class: 'site_link', target: '_blank', onclick: 'window.open(this);return false'
  .usage_info
    ul
      li.views
        em Views: 1,000
      li.video_tags
        em Videos: 1,000
      li.tags
        em –

javascript:
  $(document).ready(function() {
    ScoutSublimeVideo.carousel = new ScoutSublimeVideo.Carousel({ images: #{raw @images} });
  });

app/views/carousel/new_active_sites_week.html.slim
= title "New Active Sites of Week #{l(@day, format: :d_b_Y)}"

.hidden_form
  = form_tag new_active_sites_week_url(l(@day - 1.week, format: :Y_m_d)), method: 'get', id: 'backward' do
    = submit_tag '-'

.hidden_form
  = form_tag new_active_sites_week_url(l(@day + 1.week, format: :Y_m_d)), method: 'get', id: 'forward' do
    = submit_tag '+'

= render 'carousel'

app/views/carousel/new_sites_day.html.slim
= title "New Sites on #{l(@day, format: :d_b_Y)}"

.hidden_form
  = form_tag new_sites_day_url(l(@day - 1.day, format: :Y_m_d)), method: 'get', id: 'backward' do
    = submit_tag '-'

.hidden_form
  = form_tag new_sites_day_url(l(@day + 1.day, format: :Y_m_d)), method: 'get', id: 'forward' do
    = submit_tag '+'

= render 'carousel'

app/views/layouts/application.html.slim
doctype html
html
  head
    title= "SublimeVideo Scout - #{yield(:title)}"
    = stylesheet_link_tag 'application', media: 'all'
    = yield :stylesheet
    = javascript_include_tag 'application', '//use.typekit.com/frv0zff.js'
    = javascript_tag 'try{Typekit.load();}catch(e){}'
    = csrf_meta_tags

  body
    = yield

    #footer
      | Copyright © 2012-2013 Jilion